<a href="https://colab.research.google.com/github/desouki76/Ahmed/blob/main/Copy_of_NLP_News_Categories_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt  # drawing
import pandas as pd
import seaborn  as sns
#تقسيم البيانات
from sklearn.model_selection import train_test_split

In [4]:
# i can read json files
df= pd.read_json('/content/News_Category_Dataset_v3.json', lines=True)
df.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

In [5]:
df.shape  #get data size rows "?" and columnds = "?"

(209527, 6)

In [6]:
df['link']   # اعرض احد عواميد

0         https://www.huffpost.com/entry/covid-boosters-...
1         https://www.huffpost.com/entry/american-airlin...
2         https://www.huffpost.com/entry/funniest-tweets...
3         https://www.huffpost.com/entry/funniest-parent...
4         https://www.huffpost.com/entry/amy-cooper-lose...
                                ...
209522    https://www.huffingtonpost.com/entry/rim-ceo-t...
209523    https://www.huffingtonpost.com/entry/maria-sha...
209524    https://www.huffingtonpost.com/entry/super-bow...
209525    https://www.huffingtonpost.com/entry/aldon-smi...
209526    https://www.huffingtonpost.com/entry/dwight-ho...
Name: link, Length: 209527, dtype: object

In [7]:
df['headline'].iloc[0]  #اعرض اول ROw

'Over 4 Million Americans Roll Up Sleeves For Omicron-Targeted COVID Boosters'

In [8]:
#how many catgory i have count them for me
df['category'].value_counts()

category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64

In [9]:
df=pd.read_json('/content/News_Category_Dataset_v3.json', lines=True)[['headline','category']]
#import only two col from the table but as u need only 2 col dotn forget two [[]]
df.head()

                                            headline   category
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY
3  The Funniest Tweets From Parents This Week (Se...  PARENTING
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS

In [10]:
# we can نختصر و تسخدم ششويه
#اول  حجه نقرا عدد ال feauers
df['category'].unique()

array(['U.S. NEWS', 'COMEDY', 'PARENTING', 'WORLD NEWS', 'CULTURE & ARTS',
       'TECH', 'SPORTS', 'ENTERTAINMENT', 'POLITICS', 'WEIRD NEWS',
       'ENVIRONMENT', 'EDUCATION', 'CRIME', 'SCIENCE', 'WELLNESS',
       'BUSINESS', 'STYLE & BEAUTY', 'FOOD & DRINK', 'MEDIA',
       'QUEER VOICES', 'HOME & LIVING', 'WOMEN', 'BLACK VOICES', 'TRAVEL',
       'MONEY', 'RELIGION', 'LATINO VOICES', 'IMPACT', 'WEDDINGS',
       'COLLEGE', 'PARENTS', 'ARTS & CULTURE', 'STYLE', 'GREEN', 'TASTE',
       'HEALTHY LIVING', 'THE WORLDPOST', 'GOOD NEWS', 'WORLDPOST',
       'FIFTY', 'ARTS', 'DIVORCE'], dtype=object)

In [11]:
#picl up what i need only to my task
des_cat = ['CRIME','COMEDY' ,'EDUCATION','SPORTS']

new_df=df[df['category'].isin(des_cat)]  # هات الRows  الى موجود فى القائمه الى فوق سطر الى قبل منها

new_df.head()

                                             headline category
2   23 Of The Funniest Tweets About Cats And Dogs ...   COMEDY
17  Maury Wills, Base-Stealing Shortstop For Dodge...   SPORTS
26  Las Vegas Aces Win First WNBA Title, Chelsea G...   SPORTS
61  Boston Marathon To Make Race More Inclusive Fo...   SPORTS
62  Anthony Varvaro, MLB Pitcher Turned Transit Co...   SPORTS

In [12]:
new_df['category'].value_counts()

category
COMEDY       5400
SPORTS       5077
CRIME        3562
EDUCATION    1014
Name: count, dtype: int64

In [14]:
#Handle un balnce by SMOTE
import pandas as pd
from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

In [15]:
df.head()

                                            headline   category
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY
3  The Funniest Tweets From Parents This Week (Se...  PARENTING
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS

In [16]:
new_df.head()

                                             headline category
2   23 Of The Funniest Tweets About Cats And Dogs ...   COMEDY
17  Maury Wills, Base-Stealing Shortstop For Dodge...   SPORTS
26  Las Vegas Aces Win First WNBA Title, Chelsea G...   SPORTS
61  Boston Marathon To Make Race More Inclusive Fo...   SPORTS
62  Anthony Varvaro, MLB Pitcher Turned Transit Co...   SPORTS

In [19]:
new_df['category_encoded'] = new_df['category'].map({'CRIME': 0, 'COMEDY': 1, 'EDUCATION': 2, 'SPORTS': 3})

/tmp/ipython-input-3866313548.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['category_encoded'] = new_df['category'].map({'CRIME': 0, 'COMEDY': 1, 'EDUCATION': 2, 'SPORTS': 3})

In [22]:
print (new_df['headline'].iloc[0])
print (new_df['category_encoded'].iloc[0])

23 Of The Funniest Tweets About Cats And Dogs This Week (Sept. 17-23)
1

In [34]:
#split Data
X=new_df['headline']
y=new_df['category_encoded']
#split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=new_df.category_encoded)

In [35]:
print("Original training set distribution:", Counter(y_train))

Original training set distribution: Counter({1: 4320, 3: 4061, 0: 2850, 2: 811})

In [50]:
# # Apply SMOTE
# smote = SMOTE(random_state=42, sampling_strategy='auto')
# # 'auto' means balance all classes

# X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

# print("Resampled training set distribution:", Counter(y_resampled))

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [45]:

# Step 1: Convert text into numeric vectors (TF-IDF)

vectorizer = TfidfVectorizer(max_features=5000)  # limit features
X_tfidf = vectorizer.fit_transform(X).toarray()

In [48]:
#split
#split Data
X=new_df['headline']
y=new_df['category_encoded']
#split data
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42, stratify=new_df.category_encoded)

In [49]:
# Step 3: Apply SMOTE
smote = SMOTE(random_state=42, sampling_strategy="auto")
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

print("Resampled training set distribution:", Counter(y_resampled))

Resampled training set distribution: Counter({2: 4320, 1: 4320, 3: 4320, 0: 4320})