<a href="https://colab.research.google.com/github/desouki76/Ahmed/blob/main/TwitterFeedback_%2Bve_ve_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Binary Text Classfcaiton [+ve / - Ve for twittes] fille have 5000 +Ve Twiites and file have -Ve Twittes

# Libraires

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk

In [4]:
from numpy import random
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
#from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
#from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
#from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, SimpleRNN
from sklearn.preprocessing import LabelEncoder

In [5]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tap')
nltk.download('omw-1.4')
nltk.download('twitter_samples')

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')   # <— this is the new one in NLTK 3.9+
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Error loading punkt_tap: Package 'punkt_tap' not found in
[nltk_data]     index
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package twitter_samples to /root/nltk_data...
[nltk_data]   Unzipping corpora/twitter_samples.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [6]:
stop_words = stopwords.words('english')  # i call stope of words of english langauge
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

In [7]:
positive_tweets = nltk.corpus.twitter_samples.strings('positive_tweets.json')
# we call class of 5000  postive twittes
negative_tweets = nltk.corpus.twitter_samples.strings('negative_tweets.json')
# we call class of 5000 negtive twittes and we put it in the varable

In [8]:
pd.DataFrame(positive_tweets).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5000 non-null   object
dtypes: object(1)
memory usage: 39.2+ KB

In [9]:
pd.DataFrame(negative_tweets).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5000 non-null   object
dtypes: object(1)
memory usage: 39.2+ KB

# Fucaiton to clean twittes

In [10]:
pd.DataFrame(positive_tweets).head()

                                                   0
0  #FollowFriday @France_Inte @PKuchly57 @Milipol...
1  @Lamb2ja Hey James! How odd :/ Please call our...
2  @DespiteOfficial we had a listen last night :)...
3                               @97sides CONGRATS :)
4  yeaaaah yippppy!!!  my accnt verified rqst has...

In [11]:
#function to clean twittes
def clean_text(tweet):
    tweet=re.sub(r'http\S+','',tweet) #Plass, @mohamed remover https \S+ any no white space after http
    tweet=re.sub(r'@[A-Za-z0-9_]+','',tweet) #
    tweet=re.sub(r'[^\w\s]','',tweet)
    tweet=re.sub(r'\d+','',tweet)
    tweet=re.sub(r'\s+',' ',tweet)
    tweet=re.sub(r'\s+[a-zA-Z]\s+',' ',tweet)
    tweet=re.sub(r'^[a-zA-Z]\s+',' ',tweet)
    tweet=re.sub(r'\s$',' ',tweet)

    return tweet

In [12]:
# creat function to clean tweets and pre preoss as NLP
def preprocess_tweet(tweets):
    clean_tweets=[]
    for tweet in tweets:
      clean_tweet = clean_text(tweet)
      clean_tweet = nltk.word_tokenize(clean_tweet)
      #tweet_tokens=word_tokenize(tweet)
      #clean_tweet=[word for word in clean_tweet if word not in stop_words]
      #clean_tweet=[lemmatizer.lemmatize(word) for word in clean_tweet]

      #apply "lower case" on all tweets if the word.lower() not in stop words
      clean_tweet =[word.lower() for word in clean_tweet if word.lower() not in stop_words]
      #Apply stemmer رد الكلمه الى اصلها
      clean_tweet=[stemmer.stem(word) for word in clean_tweet]
      clean_tweet=[lemmatizer.lemmatize(word) for word in clean_tweet]
      clean_tweet = [word for word in clean_tweet if len(word) >= 3]
      #delet all words that is 2 letters only
      clean_tweets.append(clean_tweet)
    return clean_tweets

In [13]:
#Apply the prvouis fucation pre process (clean, stop words, lower case, limtizer Port stemmer)
positive_tweets_1=preprocess_tweet(positive_tweets)
negative_tweets_1=preprocess_tweet(negative_tweets)

now tweets are clean lower case limitzed Portstemmed toknized to words

In [14]:

# import sys
# sys.setrecursionlimit(10000)  # allow deeper printing if needed

# import numpy as np
# np.set_printoptions(threshold=np.inf)  # show full arrays

# pd.set_option('display.max_colwidth', None)
# pd.set_option('display.max_rows', None)

In [15]:
positive_tweets_1

[['followfriday', 'top', 'engag', 'member', 'commun', 'week'],
 ['hey',
  'jame',
  'odd',
  'plea',
  'call',
  'contact',
  'centr',
  'abl',
  'assist',
  'mani',
  'thank'],
 ['listen', 'last', 'night', 'bleed', 'amaz', 'track', 'scotland'],
 ['congrat'],
 ['yeaaaah',
  'yippppi',
  'accnt',
  'verifi',
  'rqst',
  'succeed',
  'got',
  'blue',
  'tick',
  'mark',
  'profil',
  'day'],
 ['one', 'irresist', 'flipkartfashionfriday'],
 ['dont',
  'like',
  'keep',
  'love',
  'custom',
  'wait',
  'long',
  'hope',
  'enjoy',
  'happi',
  'friday',
  'lwwf'],
 ['second',
  'thought',
  'there',
  'enough',
  'time',
  'new',
  'short',
  'enter',
  'system',
  'sheep',
  'must',
  'buy'],
 ['jgh', 'bayan', 'bye'],
 ['act',
  'mischiev',
  'call',
  'etl',
  'layer',
  'inhous',
  'wareh',
  'app',
  'katamari',
  'well',
  'name',
  'impli'],
 ['followfriday', 'top', 'influenc', 'commun', 'week'],
 ['wouldnt', 'love', 'bigjuicyselfi'],
 ['follow', 'amp', 'follow', 'back'],
 ['perfect', 'alreadi', 'know', 'what', 'wait'],
 ['great',
  'new',
  'opportun',
  'junior',
  'triathlet',
  'age',
  'gatorad',
  'seri',
  'get',
  'entri'],
 ['lay', 'greet', 'card', 'rang', 'print', 'today', 'love', 'job'],
 ['friend', 'lunch', 'yummmm', 'nostalgia'],
 ['conflict', 'thank', 'help', 'here', 'screenshot', 'work'],
 ['liv'],
 ['hello', 'need', 'know', 'someth', 'twitter', 'sure', 'thing'],
 ['followfriday', 'top', 'new', 'follow', 'commun', 'week'],
 ['ive',
  'heard',
  'four',
  'season',
  'pretti',
  'dope',
  'penthous',
  'obv',
  'gobigorgohom',
  'fun',
  'yall'],
 ['yeah', 'suppos', 'lol', 'chat', 'bit'],
 ['hello', 'get', 'youth', 'job', 'opportun', 'follow', 'gtgt'],
 ['havent', 'seen', 'year'],
 ['thank'],
 ['hope',
  'rest',
  'night',
  'goe',
  'quickli',
  'bed',
  'got',
  'music',
  'fix',
  'time',
  'dream'],
 ['spiritu',
  'ritual',
  'festiv',
  'népal',
  'begin',
  'lineup',
  'left',
  'lineup',
  'see'],
 ['hey', 'sarah', 'send', 'email', 'bitsycom', 'well', 'help', 'asap'],
 ['lol'],
 ['kik',
  'hatessuc',
  'kik',
  'kikm',
  'lgbt',
  'tinder',
  'nsfw',
  'akua',
  'cumshot'],
 ['come', 'hous'],
 ['nsn_supplement',
  'effect',
  'press',
  'releas',
  'distribut',
  'result',
  'link',
  'remov',
  'pressreleas',
  'newsdistribut'],
 ['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love'],
 ['everyon', 'watch', 'documentari', 'earthl', 'youtub'],
 ['follow', 'amp', 'follow', 'back'],
 ['followfriday', 'top', 'support', 'commun', 'week'],
 ['buuuuuuuut', 'well'],
 ['look', 'forward', 'visit', 'next', 'week', 'letsgetmessi'],
 ['make', 'feel', 'better', 'never', 'see', 'anyon', 'kpop', 'flesh'],
 ['good', 'girl', 'best', 'wish'],
 ['great', 'enough', 'reason', 'listen', 'one', 'epic', 'soundtrack'],
 ['thank', 'shout', 'great', 'friday'],
 ['video', 'playlist', 'back', 'twitch', 'today', 'leagu'],
 ['would', 'love', 'see', 'dear', 'jordan', 'wait'],
 ['okay', 'thank'],
 ['like', 'fake', 'gameplay', 'haha', 'kid', 'kid', 'good', 'stuff'],
 ['yeah', 'exactli'],
 ['new', 'product', 'line', 'etsi', 'shop', 'check', 'boxroomcraft'],
 ['hope', 'vacat', 'great'],
 ['recharg', 'normal', 'come', 'charger', 'buy'],
 ['followfriday', 'top', 'engag', 'member', 'commun', 'week'],
 ['well', 'she', 'asleep', 'one', 'talk', 'sooo', 'someon', 'text'],
 ['suppos', 'bet', 'hell', 'blue', 'fit', 'hear', 'speech', 'today', 'piti'],
 ['green',
  'garden',
  'midnight',
  'sun',
  'beauti',
  'canal',
  'dasvidaniya',
  'till',
  'next',
  'visit'],
 ['scout', 'futur', 'wlan', 'pro', 'confer', 'asia'],
 ['good', 'better', 'chang', 'lollipop'],
 ['nez', 'agnezmo'],
 ['follow', 'plea', 'big', 'dream'],
 ['oley'],
 ['mama', 'reason', 'stand', 'stronger'],
 ['follow', 'amp', 'follow', 'back'],
 ['god', 'misti', 'babi', 'cute'],
 ['love', 'blue', 'flipkartfashionfriday'],
 ['woohoo', 'cant', 'wait', 'sign', 'yet', 'still', 'think', 'mka'],
 ['liam', 'access'],
 ['welcom'],
 ['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via'],
 ['shouldnt', 'surprisedy', 'amaz', 'figur'],
 ['followfriday', 'top', 'influenc', 'commun', 'week'],
 ['happybirthdayemilybett', 'wish', 'best', 'beautifulsweettalentedamaz'],
 ['plan', 'day', 'drain', 'great'],
 ['got', 'love', 'timezon'],
 ['parent',
  'proud',
  'lol',
  'least',
  'mayb',
  'sometim',
  'get',
  'happi',
  'grade'],
 ['grand'],
 ['manila_bro', 'chosen', 'follow', 'twitter', 'thank', 'follow'],
 ['sure', 'let', 'know', 'your', 'aroundat', 'side', 'world', 'take', 'care'],
 ['followfriday', 'top', 'new', 'follow', 'commun', 'week'],
 ['final', 'fuck', 'weekend'],
 ['real'],
 ['thank'],
 ['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love'],
 ['join', 'hushedcallwithfraydo', 'call', 'amp', 'gift', 'got', 'get'],
 ['yeahhh'],
 ['amp', 'make', 'night', 'better'],
 ['join', 'hushedpinwithsammi', 'event', 'might', 'get', 'text', 'day', 'luv'],
 ['would', 'realli', 'appreci', 'share', 'video', 'around'],
 ['hello', 'get', 'youth', 'job', 'opportun', 'follow', 'gtgt'],
 ['wow', 'beauti', 'tom'],
 ['love'],
 ['video', 'playlist', 'back', 'twitch', 'today', 'leagu'],
 ['followfriday', 'top', 'support', 'commun', 'week'],
 ['follow', 'amp', 'follow', 'back'],
 ['gym', 'monday', 'cant', 'wait', 'like'],
 ['hey', 'here', 'invit', 'join', 'scope', 'influenc'],
 ['friend', 'know'],
 ['wait', 'nude'],
 ['sleep'],
 ['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via'],
 ['birthday', 'week', 'today'],
 ['want', 'your', 'tshirt', 'cool'],
 ['haw', 'phela', 'look', 'like', 'mom', 'obvious', 'look', 'like'],
 ['princ', 'charm', 'stage'],
 ['realli', 'good', 'luck'],
 ['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via'],
 ['followfriday', 'top', 'engag', 'member', 'commun', 'week'],
 ['tyler', 'hipster', 'glass'],
 ['hey', 'marti', 'glad', 'see', 'twitter'],
 ['join', 'today'],
 ['done', 'thank'],
 ['alreadi', 'afternoon', 'let', 'read', 'kahfi', 'day', 'finish'],
 ['ohmyg',
  'yaya',
  'dub',
  'done',
  'stalk',
  'accnt',
  'gondooo',
  'moo',
  'tologooo',
  'haha'],
 ['here', 'invit', 'becom', 'scope', 'influenc', 'detail'],
 ['followfriday', 'top', 'influenc', 'commun', 'week'],
 ['thank', 'zzz'],
 ['physiotherapi', 'friday', 'hashtag', 'today', 'custom'],
 ['know', 'monica', 'miss', 'yeah', 'sound', 'good'],
 ['good', 'morn', 'beauti', 'that', 'take'],
 ['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love'],
 ['yeah', 'definit', 'tri', 'tonight', 'took', 'advic', 'treviso'],
 ['follow', 'amp', 'follow', 'back'],
 ['would',
  'like',
  'concert',
  'let',
  'know',
  'citi',
  'countri',
  'ill',
  'start',
  'work',
  'thank'],
 ['fine', 'gorgeou', 'friday', 'friend'],
 ['oven',
  'roast',
  'garlic',
  'oliv',
  'oil',
  'sun',
  'dri',
  'tomato',
  'dri',
  'basil',
  'centuri',
  'tuna'],
 ['right', 'back', 'atchya', 'great', 'day', 'everyon'],
 ['doesnt', 'even', 'follow', 'back'],
 ['futur', 'almost'],
 ['followfriday', 'top', 'new', 'follow', 'commun', 'week'],
 ['chanc'],
 ['cheer'],
 ['ice', 'cream'],
 ['agre'],
 ['heheheh', 'that', 'point'],
 ['next', 'time', 'stay', 'home'],
 ['thank'],
 ['followfriday', 'top', 'support', 'commun', 'week'],
 ['soon', 'promis'],
 ['web', 'whatsapp', 'volta', 'funcionar', 'com', 'iphon', 'jailbroken'],
 ['plan',
  'watch',
  'later',
  'min',
  'leia',
  'appear',
  'hologram',
  'messag',
  'obi',
  'wan',
  'sit',
  'luke'],
 ['inter', 'ucl', 'arsen', 'small', 'team', 'right'],
 ['pas',
  'dewsburi',
  'railway',
  'station',
  'dew',
  'dewsburi',
  'west',
  'yorkshir'],
 ['smh'],
 ['live', 'scotland', 'strang', 'imagin', 'megan'],
 ['masaantoday',
  'masaantoday',
  'shweta',
  'tripathi',
  'masaantoday',
  'masaantoday'],
 ['kurta', 'mom', 'half', 'number', 'wsalelov'],
 ['hello', 'back', 'larri'],
 ['anyway', 'friday', 'look', 'kinda', 'gooood'],
 ['follow', 'amp', 'follow', 'back'],
 ['lol', 'well', 'that', 'life', 'thank', 'god', 'enn'],
 ['sure', 'could', 'warmup', 'morn', 'come', 'bath'],
 ['dum',
  'dum',
  'andar',
  'ram',
  'sampath',
  'sona',
  'mohapatra',
  'amp',
  'samantha',
  'edward',
  'mein',
  'tulan',
  'razi',
  'razi',
  'wah',
  'that',
  'josh'],
 ['alway', 'smile'],
 ['pictur'],
 ['thank', 'time', 'right', 'that', 'perfect', 'time'],
 ['followfriday', 'top', 'engag', 'member', 'commun', 'week'],
 ['know'],
 ['giveitup',
  'alreadi',
  'given',
  'subsidi',
  'long',
  'back',
  'initi',
  'propos',
  'feel',
  'delight',
  'done'],
 ['miss', 'yesterday'],
 ['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love'],
 ['lmaoo', 'best', 'song', 'ever', 'shall', 'littl', 'throwback', 'week'],
 ['outli', 'island', 'cheung', 'chau', 'mui', 'wotot', 'differ'],
 ['kfckitchentour', 'kitchen', 'clean', 'total', 'amaz'],
 ['follow', 'amp', 'follow', 'back'],
 ['cusp', 'test', 'water', 'hope', 'reward'],
 ['followfriday', 'top', 'influenc', 'commun', 'week'],
 ['arummzz',
  'let',
  'ill',
  'drive',
  'travel',
  'travel',
  'yogyakarta',
  'jeep',
  'indonesia',
  'instamood'],
 ['anyon', 'wan', 'skype'],
 ['may', 'look', 'bit', 'real', 'nice', 'friendli', 'girl'],
 ['like', 'pretend'],
 ['watch', 'concert', 'film'],
 ['congratul',
  'your',
  'winner',
  'cheesydelight',
  'contest',
  'plea',
  'address',
  'contact',
  'number'],
 ['great', 'weekend', 'guy'],
 ['followfriday', 'top', 'new', 'follow', 'commun', 'week'],
 ['cool', 'see', 'film', 'today'],
 ['check', 'email', 'market', 'wont', 'regret', 'buy'],
 ['lol', 'come', 'join', 'see', 'around', 'hour', 'leav', 'without', 'delay'],
 ['actual',
  'easi',
  'like',
  'must',
  'station',
  'guess',
  'train',
  'take',
  'least',
  'hour',
  'shift',
  'engin',
  'etc'],
 ['sunburn', 'peel'],
 ['visit', 'blog', 'thank'],
 ['would',
  'like',
  'concert',
  'let',
  'know',
  'citi',
  'countri',
  'ill',
  'start',
  'work',
  'thank'],
 ['talk', 'help'],
 ['huge', 'amp', 'warm', 'welcom', 'final', 'complet', 'triangl'],
 ['live', 'northern', 'ireland', 'sight', 'seen'],
 ['follow', 'amp', 'follow', 'back'],
 ['followfriday', 'top', 'support', 'commun', 'week'],
 ['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via'],
 ['feel',
  'smthng',
  'smthng',
  'ulolwanna',
  'hug',
  'uxoxolov',
  'jaann',
  'take',
  'care'],
 ['thank', 'mom'],
 ['thank', 'topnewfollow', 'happi', 'connect'],
 ['wonder',
  'thing',
  'made',
  'feel',
  'fluffi',
  'insid',
  'great',
  'pirouett',
  'moo'],
 ['trip', 'philli', 'decemb', 'love', 'come', 'dude'],
 ['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love'],
 ['question', 'flaw', 'pain', 'doesnt', 'negat', 'strength'],
 ['went', 'solo', 'move', 'werent', 'made'],
 ['hey',
  'fav',
  'nirvana',
  'song',
  'smell',
  'like',
  'teen',
  'spirit',
  'rip',
  'ami',
  'winehous'],
 ['followfriday', 'top', 'engag', 'member', 'commun', 'week'],
 ['let',
  'ill',
  'drive',
  'travel',
  'travel',
  'yogyakarta',
  'jeep',
  'indonesia',
  'instamood'],
 ['name',
  'coupl',
  'yet',
  'tomhiddleston',
  'elizabetholsen',
  'yaytheylookgreat'],
 ['love', 'goodnight', 'vid', 'wake', 'love', 'one'],
 ['weekend', 'gon', 'shoot', 'love', 'pictur', 'made', 'last', 'time'],
 ['anyway'],
 ['itti', 'bitti', 'teeni', 'bikini'],
 ['join', 'hushedpinwithsammi', 'event', 'might', 'get', 'text', 'day', 'luv'],
 ['alway',
  'much',
  'fun',
  'hour',
  'get',
  'togeth',
  'end',
  'night',
  'ice',
  'cream',
  'xfile',
  'content'],
 ['easi'],
 ['surpris', 'dont', 'see', 'bit', 'rain', 'today'],
 ['follow', 'amp', 'follow', 'back'],
 ['fabul', 'friday', 'keep', 'fantast', 'work'],
 ['plea',
  'follow',
  'plea',
  'follow',
  'love',
  'alway',
  'forev',
  'belieb',
  'love'],
 ['followfriday', 'top', 'influenc', 'commun', 'week'],
 ['morn'],
 ['good', 'hear'],
 ['nighti', 'night', 'dont', 'let', 'bed', 'bug', 'bite'],
 ['beauti', 'bracelet', 'good', 'idea'],
 ['wait', 'foundri'],
 ['like', 'game'],
 ['make', 'sen', 'didnt', 'see', 'pic', 'phone', 'last', 'night', 'woot'],
 ['derek', 'could', 'tri', 'use', 'parkshar', 'gloucestershir'],
 ['aaaahhh', 'man', 'track', 'traffic', 'stress', 'reliev'],
 ['followfriday', 'top', 'new', 'follow', 'commun', 'week'],
 ['howr', 'today', 'dear'],
 ['hear', 'guy', 'want', 'arbeloa'],
 ['turn', 'daysomg', 'least', 'year', 'differ'],
 ['well', 'say', 'europ', 'rise', 'find', 'hard', 'believ'],
 ['wsalelov', 'uncount', 'coz', 'love', 'unlimit'],
 ['cours', 'teamposit'],
 ['love', 'aldub'],
 ['thank', 'rita'],
 ['could', 'plea', 'info', 'wed', 'happi', 'help'],
 ['way', 'boy'],
 ['hope', 'get', 'lot', 'nice', 'gift'],
 ['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love'],
 ['followfriday', 'top', 'support', 'commun', 'week'],
 ['true'],
 ['video', 'playlist', 'back', 'twitch', 'today', 'leagu'],
 ['sethi', 'high'],
 ['exe', 'skeem', 'saam'],
 ['peopl', 'make', 'smile'],
 ['thank', 'invit'],
 ['polit',
  'izzat',
  'wese',
  'trust',
  'khawateen',
  'sath',
  'selfi',
  'say',
  'mana',
  'kar',
  'deya'],
 ['thank', 'that', 'friday', 'even', 'sort'],
 ['smart'],
 ['nice', 'hair', 'tbh'],
 ['year'],
 ['jacob', 'mampg', 'upgrad'],
 ['nice', 'tee', 'man'],
 ['happi', 'famili', 'vacat', 'pic'],
 ['sleep', 'would', 'nice'],
 ['your', 'read', 'your', 'beauti', 'like', 'read'],
 ['talk', 'one', 'person', 'two', 'convers'],
 ['skype', 'fun'],
 ['onlin'],
 ['friday'],
 ['followfriday', 'top', 'engag', 'member', 'commun', 'week'],
 ['someth',
  'get',
  'friday',
  'great',
  'start',
  'great',
  'day',
  'mclaren',
  'fridayfeel',
  'tgif'],
 ['follow', 'amp', 'follow', 'back'],
 ['squar', 'enix', 'bissmillah', 'allah'],
 ['train',
  'socent',
  'startup',
  'week',
  'wed',
  'love',
  'drop',
  'your',
  'arnd',
  'town'],
 ['basic', 'piss', 'cup', 'test'],
 ['next'],
 ['also', 'twitter', 'terribl', 'complic', 'discus'],
 ['snapchat',
  'lynettelow',
  'snapchat',
  'kikmenow',
  'snapm',
  'hot',
  'snapchat',
  'amazon',
  'kikmeguy'],
 ['look', 'forward', 'hour', 'shift', 'today'],
 ['defin', 'agre', 'grow', 'sport', 'drop', 'email', 'detail', 'see'],
 ['last'],
 ['rakyat', 'keep', 'visit', 'blog', 'read', 'write'],
 ['ever',
  'sinc',
  'mention',
  'fli',
  'fish',
  'day',
  'get',
  'follow',
  'promot',
  'post',
  'lol',
  'cyber',
  'stalk'],
 ['ourdaughtersourprid', 'mypapamyprid', 'proud', 'papa', 'coach'],
 ['great', 'talk'],
 ['never', 'see', 'posit', 'kha', 'could', 'also', 'mention', 'atleast'],
 ['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love'],
 ['mango', 'lassi', 'monti', 'marvel', 'though', 'suspect', 'that', 'meant'],
 ['followfriday', 'top', 'influenc', 'commun', 'week'],
 ['haha', 'time', 'come', 'touch', 'kepler', 'chalna', 'hai'],
 ['follow', 'amp', 'follow', 'back'],
 ['thankyou', 'pretti'],
 ['definit', 'hazel', 'food', 'market', 'brooklyn', 'pta', 'gtgt'],
 ['still', 'awak'],
 ['okayi'],
 ['awww', 'thank'],
 ['surpris',
  'least',
  'okay',
  'see',
  'doc',
  'afternoon',
  'yorkshir',
  'splendid',
  'though'],
 ['spam',
  'folder',
  'wow',
  'huge',
  'amount',
  'need',
  'travel',
  'nigeria',
  'claim'],
 ['rted', 'good', 'luck'],
 ['leg', 'hurt', 'bad'],
 ['get', 'mine', 'saturday'],
 ['thaaank', 'decemb', 'puhon'],
 ['happinessss'],
 ['true',
  'chang',
  'tnc',
  'without',
  'prior',
  'notif',
  'could',
  'use',
  'last',
  'night'],
 ['probabl', 'find', 'funni'],
 ['fat', 'probabl', 'ate', 'yuna'],
 ['fun', 'tamesid'],
 [],
 ['your', 'welcom'],
 ['googl', 'account'],
 ['call', 'scouser', 'everyth', 'hope', 'zoe', 'well', 'mate'],
 ['right', 'liter', 'like', 'mayb', 'get', 'peopl', 'actual', 'know', 'theyr'],
 ['samee', 'rest', 'well'],
 ['happi',
  'birthday',
  'edgar',
  'hope',
  'good',
  'one',
  'keep',
  'updat',
  'travel',
  'log'],
 ['hello'],
 ['bring', 'abe'],
 ['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via'],
 ['someon', 'talk'],
 ['never', 'ever', 'meet'],
 ['come', 'man'],
 ['follow', 'amp', 'follow', 'back'],
 ['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love'],
 ['sigh', 'dreamili', 'pout', 'come', 'bath', 'eye', 'quacketyquack'],
 ['happi', 'birthday', 'love'],
 ['cheer'],
 ['funni', 'happen', 'phil'],
 ['call', 'del', 'amp', 'rodder'],
 ['may', 'like', 'play', 'newest', 'gamejam', 'game', 'would', 'happi'],
 ['great', 'irish', 'literatur', 'realli', 'inaccess', 'without', 'irish'],
 ['yeah', 'fun', 'flipkartfashionfriday'],
 ['nice', 'music', 'check'],
 ['strang', 'kareena', 'fan', 'know', 'kareena', 'fan'],
 ['hello', 'get', 'youth', 'job', 'opportun', 'follow', 'gtgt'],
 ['better'],
 ['cool', 'look'],
 ['beauti'],
 ['play', 'brain', 'dot', 'braindot'],
 ['that', 'fair', 'enough', 'wouldnt', 'rush', 'back', 'either'],
 ['brandi', 'drop', 'selfi', 'fun'],
 ['follow', 'amp', 'follow', 'back'],
 ['carniv', 'men', 'put', 'mask', 'mask', 'xavier', 'forneret'],
 ['jennif',
  'check',
  'site',
  'wan',
  'get',
  'free',
  'ball',
  'pool',
  'coin',
  'thank'],
 ['beauti', 'edit', 'trish', 'love'],
 ['grate',
  'happi',
  'post',
  'three',
  'thing',
  'your',
  'grate',
  'today',
  'comment'],
 ['love', 'wakeup', 'besid', 'amp', 'real', 'dirtydirti', 'sex'],
 ['lmaooo', 'hot', 'like', 'loui', 'hot'],
 ['gon',
  'throw',
  'idea',
  'caus',
  'theyr',
  'bad',
  'inspir',
  'think',
  'someth',
  'much',
  'better'],
 ['best', 'twoof', 'follow', 'wkend'],
 ['wish', 'could', 'mayb', 'one', 'year'],
 ['hey', 'guy'],
 ['think', 'need', 'bed', 'kind', 'exhaust', 'good', 'night', 'twitter'],
 ['thank', 'much', 'glad', 'like'],
 ['get', 'better', 'time'],
 ['kind', 'word', 'thank', 'much', 'much', 'good', 'cheltenham', 'area'],
 ['beauti', 'follow', 'plea'],
 ['werent', 'kale', 'crisp', 'ruin', 'good', 'thing'],
 ['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love'],
 ['open', 'worldwid'],
 ['get', 'fuck', 'outta'],
 ['cool', 'guy', 'sfvbeta', 'releas', 'work'],
 ['realli', 'look', 'vantast'],
 ['today', 'final', 'time', 'work', 'xcylin'],
 ['thank',
  'bundl',
  'show',
  'internet',
  'price',
  'phone',
  'realisticli',
  'pay',
  'net'],
 ['true', 'educ', 'power', 'weapon', 'use', 'chang', 'worldnelson', 'mandela'],
 ['follow', 'amp', 'follow', 'back'],
 ['recent',
  'trip',
  'jampk',
  'total',
  'love',
  'that',
  'chenab',
  'flow',
  'pakistan',
  'incredibleindia'],
 ['teenchoic', 'choiceinternationalartist', 'superjunior'],
 ['caught', 'first', 'salmon', 'today'],
 ['happi', 'friday', 'check', 'see', 'enjoy', 'superblend'],
 ['thank',
  'follow',
  'get',
  'touch',
  'youd',
  'like',
  'info',
  'project',
  'youthorguk'],
 ['plea', 'check', 'awesom', 'friend', 'stream', 'fantast', 'artist'],
 ['alma',
  'mater',
  'highschoolday',
  'clientvisit',
  'faith',
  'christian',
  'school'],
 ['good', 'luck', 'lizaminnelli', 'upcom', 'appear'],
 ['lol', 'realli', 'cant', 'believ', 'beauti', 'girl', 'like', 'singl'],
 ['never', 'listen', 'hill', 'everi'],
 ['would', 'listen', 'beat', 'went', 'wrong', 'life'],
 ['haha', 'that', 'great'],
 ['get',
  'everyth',
  'readi',
  'natur',
  'pefumeri',
  'workshop',
  'neal',
  'yard',
  'covent',
  'garden',
  'tomorrow'],
 ['fback', 'indo', 'harmo'],
 ['americano'],
 [],
 ['love', 'way'],
 ['alway', 'rememb'],
 ['aww', 'thank', 'beauti', 'pic'],
 ['head'],
 ['saw',
  'follow',
  'thought',
  'might',
  'like',
  'dark',
  'plz',
  'let',
  'know',
  'think'],
 ['smart', 'handshom', 'cute', 'juga'],
 ['hurray', 'look', 'forward', 'meet'],
 ['follow', 'amp', 'follow', 'back'],
 ['caus',
  'hate',
  'cours',
  'lol',
  'cant',
  'decid',
  'want',
  'chang',
  'take',
  'time',
  'save',
  'mayb',
  'travel'],
 ['list', 'still', 'show'],
 [],
 ['would',
  'like',
  'concert',
  'let',
  'know',
  'citi',
  'countri',
  'ill',
  'start',
  'work',
  'thank'],
 ['awesom', 'thank', 'much'],
 ['your', 'perfect'],
 ['hiya', 'email', 'web', 'exec', 'loryngoodchambercouk', 'abl', 'help'],
 ['enjoy', 'photo', 'beforewhen', 'mom', 'babi'],
 ['big', 'thx', 'kind', 'support', 'good', 'luck'],
 ['china',
  'actual',
  'girl',
  'homosexu',

In [16]:
for tweet in positive_tweets_1[:1000]:
    print(tweet)

['followfriday', 'top', 'engag', 'member', 'commun', 'week']
['hey', 'jame', 'odd', 'plea', 'call', 'contact', 'centr', 'abl', 'assist', 'mani', 'thank']
['listen', 'last', 'night', 'bleed', 'amaz', 'track', 'scotland']
['congrat']
['yeaaaah', 'yippppi', 'accnt', 'verifi', 'rqst', 'succeed', 'got', 'blue', 'tick', 'mark', 'profil', 'day']
['one', 'irresist', 'flipkartfashionfriday']
['dont', 'like', 'keep', 'love', 'custom', 'wait', 'long', 'hope', 'enjoy', 'happi', 'friday', 'lwwf']
['second', 'thought', 'there', 'enough', 'time', 'new', 'short', 'enter', 'system', 'sheep', 'must', 'buy']
['jgh', 'bayan', 'bye']
['act', 'mischiev', 'call', 'etl', 'layer', 'inhous', 'wareh', 'app', 'katamari', 'well', 'name', 'impli']
['followfriday', 'top', 'influenc', 'commun', 'week']
['wouldnt', 'love', 'bigjuicyselfi']
['follow', 'amp', 'follow', 'back']
['perfect', 'alreadi', 'know', 'what', 'wait']
['great', 'new', 'opportun', 'junior', 'triathlet', 'age', 'gatorad', 'seri', 'get', 'entri']
['lay', 'greet', 'card', 'rang', 'print', 'today', 'love', 'job']
['friend', 'lunch', 'yummmm', 'nostalgia']
['conflict', 'thank', 'help', 'here', 'screenshot', 'work']
['liv']
['hello', 'need', 'know', 'someth', 'twitter', 'sure', 'thing']
['followfriday', 'top', 'new', 'follow', 'commun', 'week']
['ive', 'heard', 'four', 'season', 'pretti', 'dope', 'penthous', 'obv', 'gobigorgohom', 'fun', 'yall']
['yeah', 'suppos', 'lol', 'chat', 'bit']
['hello', 'get', 'youth', 'job', 'opportun', 'follow', 'gtgt']
['havent', 'seen', 'year']
['thank']
['hope', 'rest', 'night', 'goe', 'quickli', 'bed', 'got', 'music', 'fix', 'time', 'dream']
['spiritu', 'ritual', 'festiv', 'népal', 'begin', 'lineup', 'left', 'lineup', 'see']
['hey', 'sarah', 'send', 'email', 'bitsycom', 'well', 'help', 'asap']
['lol']
['kik', 'hatessuc', 'kik', 'kikm', 'lgbt', 'tinder', 'nsfw', 'akua', 'cumshot']
['come', 'hous']
['nsn_supplement', 'effect', 'press', 'releas', 'distribut', 'result', 'link', 'remov', 'pressreleas', 'newsdistribut']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['everyon', 'watch', 'documentari', 'earthl', 'youtub']
['follow', 'amp', 'follow', 'back']
['followfriday', 'top', 'support', 'commun', 'week']
['buuuuuuuut', 'well']
['look', 'forward', 'visit', 'next', 'week', 'letsgetmessi']
['make', 'feel', 'better', 'never', 'see', 'anyon', 'kpop', 'flesh']
['good', 'girl', 'best', 'wish']
['great', 'enough', 'reason', 'listen', 'one', 'epic', 'soundtrack']
['thank', 'shout', 'great', 'friday']
['video', 'playlist', 'back', 'twitch', 'today', 'leagu']
['would', 'love', 'see', 'dear', 'jordan', 'wait']
['okay', 'thank']
['like', 'fake', 'gameplay', 'haha', 'kid', 'kid', 'good', 'stuff']
['yeah', 'exactli']
['new', 'product', 'line', 'etsi', 'shop', 'check', 'boxroomcraft']
['hope', 'vacat', 'great']
['recharg', 'normal', 'come', 'charger', 'buy']
['followfriday', 'top', 'engag', 'member', 'commun', 'week']
['well', 'she', 'asleep', 'one', 'talk', 'sooo', 'someon', 'text']
['suppos', 'bet', 'hell', 'blue', 'fit', 'hear', 'speech', 'today', 'piti']
['green', 'garden', 'midnight', 'sun', 'beauti', 'canal', 'dasvidaniya', 'till', 'next', 'visit']
['scout', 'futur', 'wlan', 'pro', 'confer', 'asia']
['good', 'better', 'chang', 'lollipop']
['nez', 'agnezmo']
['follow', 'plea', 'big', 'dream']
['oley']
['mama', 'reason', 'stand', 'stronger']
['follow', 'amp', 'follow', 'back']
['god', 'misti', 'babi', 'cute']
['love', 'blue', 'flipkartfashionfriday']
['woohoo', 'cant', 'wait', 'sign', 'yet', 'still', 'think', 'mka']
['liam', 'access']
['welcom']
['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via']
['shouldnt', 'surprisedy', 'amaz', 'figur']
['followfriday', 'top', 'influenc', 'commun', 'week']
['happybirthdayemilybett', 'wish', 'best', 'beautifulsweettalentedamaz']
['plan', 'day', 'drain', 'great']
['got', 'love', 'timezon']
['parent', 'proud', 'lol', 'least', 'mayb', 'sometim', 'get', 'happi', 'grade']
['grand']
['manila_bro', 'chosen', 'follow', 'twitter', 'thank', 'follow']
['sure', 'let', 'know', 'your', 'aroundat', 'side', 'world', 'take', 'care']
['followfriday', 'top', 'new', 'follow', 'commun', 'week']
['final', 'fuck', 'weekend']
['real']
['thank']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['join', 'hushedcallwithfraydo', 'call', 'amp', 'gift', 'got', 'get']
['yeahhh']
['amp', 'make', 'night', 'better']
['join', 'hushedpinwithsammi', 'event', 'might', 'get', 'text', 'day', 'luv']
['would', 'realli', 'appreci', 'share', 'video', 'around']
['hello', 'get', 'youth', 'job', 'opportun', 'follow', 'gtgt']
['wow', 'beauti', 'tom']
['love']
['video', 'playlist', 'back', 'twitch', 'today', 'leagu']
['followfriday', 'top', 'support', 'commun', 'week']
['follow', 'amp', 'follow', 'back']
['gym', 'monday', 'cant', 'wait', 'like']
['hey', 'here', 'invit', 'join', 'scope', 'influenc']
['friend', 'know']
['wait', 'nude']
['sleep']
['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via']
['birthday', 'week', 'today']
['want', 'your', 'tshirt', 'cool']
['haw', 'phela', 'look', 'like', 'mom', 'obvious', 'look', 'like']
['princ', 'charm', 'stage']
['realli', 'good', 'luck']
['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via']
['followfriday', 'top', 'engag', 'member', 'commun', 'week']
['tyler', 'hipster', 'glass']
['hey', 'marti', 'glad', 'see', 'twitter']
['join', 'today']
['done', 'thank']
['alreadi', 'afternoon', 'let', 'read', 'kahfi', 'day', 'finish']
['ohmyg', 'yaya', 'dub', 'done', 'stalk', 'accnt', 'gondooo', 'moo', 'tologooo', 'haha']
['here', 'invit', 'becom', 'scope', 'influenc', 'detail']
['followfriday', 'top', 'influenc', 'commun', 'week']
['thank', 'zzz']
['physiotherapi', 'friday', 'hashtag', 'today', 'custom']
['know', 'monica', 'miss', 'yeah', 'sound', 'good']
['good', 'morn', 'beauti', 'that', 'take']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['yeah', 'definit', 'tri', 'tonight', 'took', 'advic', 'treviso']
['follow', 'amp', 'follow', 'back']
['would', 'like', 'concert', 'let', 'know', 'citi', 'countri', 'ill', 'start', 'work', 'thank']
['fine', 'gorgeou', 'friday', 'friend']
['oven', 'roast', 'garlic', 'oliv', 'oil', 'sun', 'dri', 'tomato', 'dri', 'basil', 'centuri', 'tuna']
['right', 'back', 'atchya', 'great', 'day', 'everyon']
['doesnt', 'even', 'follow', 'back']
['futur', 'almost']
['followfriday', 'top', 'new', 'follow', 'commun', 'week']
['chanc']
['cheer']
['ice', 'cream']
['agre']
['heheheh', 'that', 'point']
['next', 'time', 'stay', 'home']
['thank']
['followfriday', 'top', 'support', 'commun', 'week']
['soon', 'promis']
['web', 'whatsapp', 'volta', 'funcionar', 'com', 'iphon', 'jailbroken']
['plan', 'watch', 'later', 'min', 'leia', 'appear', 'hologram', 'messag', 'obi', 'wan', 'sit', 'luke']
['inter', 'ucl', 'arsen', 'small', 'team', 'right']
['pas', 'dewsburi', 'railway', 'station', 'dew', 'dewsburi', 'west', 'yorkshir']
['smh']
['live', 'scotland', 'strang', 'imagin', 'megan']
['masaantoday', 'masaantoday', 'shweta', 'tripathi', 'masaantoday', 'masaantoday']
['kurta', 'mom', 'half', 'number', 'wsalelov']
['hello', 'back', 'larri']
['anyway', 'friday', 'look', 'kinda', 'gooood']
['follow', 'amp', 'follow', 'back']
['lol', 'well', 'that', 'life', 'thank', 'god', 'enn']
['sure', 'could', 'warmup', 'morn', 'come', 'bath']
['dum', 'dum', 'andar', 'ram', 'sampath', 'sona', 'mohapatra', 'amp', 'samantha', 'edward', 'mein', 'tulan', 'razi', 'razi', 'wah', 'that', 'josh']
['alway', 'smile']
['pictur']
['thank', 'time', 'right', 'that', 'perfect', 'time']
['followfriday', 'top', 'engag', 'member', 'commun', 'week']
['know']
['giveitup', 'alreadi', 'given', 'subsidi', 'long', 'back', 'initi', 'propos', 'feel', 'delight', 'done']
['miss', 'yesterday']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['lmaoo', 'best', 'song', 'ever', 'shall', 'littl', 'throwback', 'week']
['outli', 'island', 'cheung', 'chau', 'mui', 'wotot', 'differ']
['kfckitchentour', 'kitchen', 'clean', 'total', 'amaz']
['follow', 'amp', 'follow', 'back']
['cusp', 'test', 'water', 'hope', 'reward']
['followfriday', 'top', 'influenc', 'commun', 'week']
['arummzz', 'let', 'ill', 'drive', 'travel', 'travel', 'yogyakarta', 'jeep', 'indonesia', 'instamood']
['anyon', 'wan', 'skype']
['may', 'look', 'bit', 'real', 'nice', 'friendli', 'girl']
['like', 'pretend']
['watch', 'concert', 'film']
['congratul', 'your', 'winner', 'cheesydelight', 'contest', 'plea', 'address', 'contact', 'number']
['great', 'weekend', 'guy']
['followfriday', 'top', 'new', 'follow', 'commun', 'week']
['cool', 'see', 'film', 'today']
['check', 'email', 'market', 'wont', 'regret', 'buy']
['lol', 'come', 'join', 'see', 'around', 'hour', 'leav', 'without', 'delay']
['actual', 'easi', 'like', 'must', 'station', 'guess', 'train', 'take', 'least', 'hour', 'shift', 'engin', 'etc']
['sunburn', 'peel']
['visit', 'blog', 'thank']
['would', 'like', 'concert', 'let', 'know', 'citi', 'countri', 'ill', 'start', 'work', 'thank']
['talk', 'help']
['huge', 'amp', 'warm', 'welcom', 'final', 'complet', 'triangl']
['live', 'northern', 'ireland', 'sight', 'seen']
['follow', 'amp', 'follow', 'back']
['followfriday', 'top', 'support', 'commun', 'week']
['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via']
['feel', 'smthng', 'smthng', 'ulolwanna', 'hug', 'uxoxolov', 'jaann', 'take', 'care']
['thank', 'mom']
['thank', 'topnewfollow', 'happi', 'connect']
['wonder', 'thing', 'made', 'feel', 'fluffi', 'insid', 'great', 'pirouett', 'moo']
['trip', 'philli', 'decemb', 'love', 'come', 'dude']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['question', 'flaw', 'pain', 'doesnt', 'negat', 'strength']
['went', 'solo', 'move', 'werent', 'made']
['hey', 'fav', 'nirvana', 'song', 'smell', 'like', 'teen', 'spirit', 'rip', 'ami', 'winehous']
['followfriday', 'top', 'engag', 'member', 'commun', 'week']
['let', 'ill', 'drive', 'travel', 'travel', 'yogyakarta', 'jeep', 'indonesia', 'instamood']
['name', 'coupl', 'yet', 'tomhiddleston', 'elizabetholsen', 'yaytheylookgreat']
['love', 'goodnight', 'vid', 'wake', 'love', 'one']
['weekend', 'gon', 'shoot', 'love', 'pictur', 'made', 'last', 'time']
['anyway']
['itti', 'bitti', 'teeni', 'bikini']
['join', 'hushedpinwithsammi', 'event', 'might', 'get', 'text', 'day', 'luv']
['alway', 'much', 'fun', 'hour', 'get', 'togeth', 'end', 'night', 'ice', 'cream', 'xfile', 'content']
['easi']
['surpris', 'dont', 'see', 'bit', 'rain', 'today']
['follow', 'amp', 'follow', 'back']
['fabul', 'friday', 'keep', 'fantast', 'work']
['plea', 'follow', 'plea', 'follow', 'love', 'alway', 'forev', 'belieb', 'love']
['followfriday', 'top', 'influenc', 'commun', 'week']
['morn']
['good', 'hear']
['nighti', 'night', 'dont', 'let', 'bed', 'bug', 'bite']
['beauti', 'bracelet', 'good', 'idea']
['wait', 'foundri']
['like', 'game']
['make', 'sen', 'didnt', 'see', 'pic', 'phone', 'last', 'night', 'woot']
['derek', 'could', 'tri', 'use', 'parkshar', 'gloucestershir']
['aaaahhh', 'man', 'track', 'traffic', 'stress', 'reliev']
['followfriday', 'top', 'new', 'follow', 'commun', 'week']
['howr', 'today', 'dear']
['hear', 'guy', 'want', 'arbeloa']
['turn', 'daysomg', 'least', 'year', 'differ']
['well', 'say', 'europ', 'rise', 'find', 'hard', 'believ']
['wsalelov', 'uncount', 'coz', 'love', 'unlimit']
['cours', 'teamposit']
['love', 'aldub']
['thank', 'rita']
['could', 'plea', 'info', 'wed', 'happi', 'help']
['way', 'boy']
['hope', 'get', 'lot', 'nice', 'gift']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['followfriday', 'top', 'support', 'commun', 'week']
['true']
['video', 'playlist', 'back', 'twitch', 'today', 'leagu']
['sethi', 'high']
['exe', 'skeem', 'saam']
['peopl', 'make', 'smile']
['thank', 'invit']
['polit', 'izzat', 'wese', 'trust', 'khawateen', 'sath', 'selfi', 'say', 'mana', 'kar', 'deya']
['thank', 'that', 'friday', 'even', 'sort']
['smart']
['nice', 'hair', 'tbh']
['year']
['jacob', 'mampg', 'upgrad']
['nice', 'tee', 'man']
['happi', 'famili', 'vacat', 'pic']
['sleep', 'would', 'nice']
['your', 'read', 'your', 'beauti', 'like', 'read']
['talk', 'one', 'person', 'two', 'convers']
['skype', 'fun']
['onlin']
['friday']
['followfriday', 'top', 'engag', 'member', 'commun', 'week']
['someth', 'get', 'friday', 'great', 'start', 'great', 'day', 'mclaren', 'fridayfeel', 'tgif']
['follow', 'amp', 'follow', 'back']
['squar', 'enix', 'bissmillah', 'allah']
['train', 'socent', 'startup', 'week', 'wed', 'love', 'drop', 'your', 'arnd', 'town']
['basic', 'piss', 'cup', 'test']
['next']
['also', 'twitter', 'terribl', 'complic', 'discus']
['snapchat', 'lynettelow', 'snapchat', 'kikmenow', 'snapm', 'hot', 'snapchat', 'amazon', 'kikmeguy']
['look', 'forward', 'hour', 'shift', 'today']
['defin', 'agre', 'grow', 'sport', 'drop', 'email', 'detail', 'see']
['last']
['rakyat', 'keep', 'visit', 'blog', 'read', 'write']
['ever', 'sinc', 'mention', 'fli', 'fish', 'day', 'get', 'follow', 'promot', 'post', 'lol', 'cyber', 'stalk']
['ourdaughtersourprid', 'mypapamyprid', 'proud', 'papa', 'coach']
['great', 'talk']
['never', 'see', 'posit', 'kha', 'could', 'also', 'mention', 'atleast']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['mango', 'lassi', 'monti', 'marvel', 'though', 'suspect', 'that', 'meant']
['followfriday', 'top', 'influenc', 'commun', 'week']
['haha', 'time', 'come', 'touch', 'kepler', 'chalna', 'hai']
['follow', 'amp', 'follow', 'back']
['thankyou', 'pretti']
['definit', 'hazel', 'food', 'market', 'brooklyn', 'pta', 'gtgt']
['still', 'awak']
['okayi']
['awww', 'thank']
['surpris', 'least', 'okay', 'see', 'doc', 'afternoon', 'yorkshir', 'splendid', 'though']
['spam', 'folder', 'wow', 'huge', 'amount', 'need', 'travel', 'nigeria', 'claim']
['rted', 'good', 'luck']
['leg', 'hurt', 'bad']
['get', 'mine', 'saturday']
['thaaank', 'decemb', 'puhon']
['happinessss']
['true', 'chang', 'tnc', 'without', 'prior', 'notif', 'could', 'use', 'last', 'night']
['probabl', 'find', 'funni']
['fat', 'probabl', 'ate', 'yuna']
['fun', 'tamesid']
[]
['your', 'welcom']
['googl', 'account']
['call', 'scouser', 'everyth', 'hope', 'zoe', 'well', 'mate']
['right', 'liter', 'like', 'mayb', 'get', 'peopl', 'actual', 'know', 'theyr']
['samee', 'rest', 'well']
['happi', 'birthday', 'edgar', 'hope', 'good', 'one', 'keep', 'updat', 'travel', 'log']
['hello']
['bring', 'abe']
['stat', 'day', 'arriv', 'new', 'follow', 'unfollow', 'via']
['someon', 'talk']
['never', 'ever', 'meet']
['come', 'man']
['follow', 'amp', 'follow', 'back']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['sigh', 'dreamili', 'pout', 'come', 'bath', 'eye', 'quacketyquack']
['happi', 'birthday', 'love']
['cheer']
['funni', 'happen', 'phil']
['call', 'del', 'amp', 'rodder']
['may', 'like', 'play', 'newest', 'gamejam', 'game', 'would', 'happi']
['great', 'irish', 'literatur', 'realli', 'inaccess', 'without', 'irish']
['yeah', 'fun', 'flipkartfashionfriday']
['nice', 'music', 'check']
['strang', 'kareena', 'fan', 'know', 'kareena', 'fan']
['hello', 'get', 'youth', 'job', 'opportun', 'follow', 'gtgt']
['better']
['cool', 'look']
['beauti']
['play', 'brain', 'dot', 'braindot']
['that', 'fair', 'enough', 'wouldnt', 'rush', 'back', 'either']
['brandi', 'drop', 'selfi', 'fun']
['follow', 'amp', 'follow', 'back']
['carniv', 'men', 'put', 'mask', 'mask', 'xavier', 'forneret']
['jennif', 'check', 'site', 'wan', 'get', 'free', 'ball', 'pool', 'coin', 'thank']
['beauti', 'edit', 'trish', 'love']
['grate', 'happi', 'post', 'three', 'thing', 'your', 'grate', 'today', 'comment']
['love', 'wakeup', 'besid', 'amp', 'real', 'dirtydirti', 'sex']
['lmaooo', 'hot', 'like', 'loui', 'hot']
['gon', 'throw', 'idea', 'caus', 'theyr', 'bad', 'inspir', 'think', 'someth', 'much', 'better']
['best', 'twoof', 'follow', 'wkend']
['wish', 'could', 'mayb', 'one', 'year']
['hey', 'guy']
['think', 'need', 'bed', 'kind', 'exhaust', 'good', 'night', 'twitter']
['thank', 'much', 'glad', 'like']
['get', 'better', 'time']
['kind', 'word', 'thank', 'much', 'much', 'good', 'cheltenham', 'area']
['beauti', 'follow', 'plea']
['werent', 'kale', 'crisp', 'ruin', 'good', 'thing']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['open', 'worldwid']
['get', 'fuck', 'outta']
['cool', 'guy', 'sfvbeta', 'releas', 'work']
['realli', 'look', 'vantast']
['today', 'final', 'time', 'work', 'xcylin']
['thank', 'bundl', 'show', 'internet', 'price', 'phone', 'realisticli', 'pay', 'net']
['true', 'educ', 'power', 'weapon', 'use', 'chang', 'worldnelson', 'mandela']
['follow', 'amp', 'follow', 'back']
['recent', 'trip', 'jampk', 'total', 'love', 'that', 'chenab', 'flow', 'pakistan', 'incredibleindia']
['teenchoic', 'choiceinternationalartist', 'superjunior']
['caught', 'first', 'salmon', 'today']
['happi', 'friday', 'check', 'see', 'enjoy', 'superblend']
['thank', 'follow', 'get', 'touch', 'youd', 'like', 'info', 'project', 'youthorguk']
['plea', 'check', 'awesom', 'friend', 'stream', 'fantast', 'artist']
['alma', 'mater', 'highschoolday', 'clientvisit', 'faith', 'christian', 'school']
['good', 'luck', 'lizaminnelli', 'upcom', 'appear']
['lol', 'realli', 'cant', 'believ', 'beauti', 'girl', 'like', 'singl']
['never', 'listen', 'hill', 'everi']
['would', 'listen', 'beat', 'went', 'wrong', 'life']
['haha', 'that', 'great']
['get', 'everyth', 'readi', 'natur', 'pefumeri', 'workshop', 'neal', 'yard', 'covent', 'garden', 'tomorrow']
['fback', 'indo', 'harmo']
['americano']
[]
['love', 'way']
['alway', 'rememb']
['aww', 'thank', 'beauti', 'pic']
['head']
['saw', 'follow', 'thought', 'might', 'like', 'dark', 'plz', 'let', 'know', 'think']
['smart', 'handshom', 'cute', 'juga']
['hurray', 'look', 'forward', 'meet']
['follow', 'amp', 'follow', 'back']
['caus', 'hate', 'cours', 'lol', 'cant', 'decid', 'want', 'chang', 'take', 'time', 'save', 'mayb', 'travel']
['list', 'still', 'show']
[]
['would', 'like', 'concert', 'let', 'know', 'citi', 'countri', 'ill', 'start', 'work', 'thank']
['awesom', 'thank', 'much']
['your', 'perfect']
['hiya', 'email', 'web', 'exec', 'loryngoodchambercouk', 'abl', 'help']
['enjoy', 'photo', 'beforewhen', 'mom', 'babi']
['big', 'thx', 'kind', 'support', 'good', 'luck']
['china', 'actual', 'girl', 'homosexu', 'love', 'himher', 'either', 'way', 'hyungbot']
['caus', 'like', 'lot']
['give', 'time', 'fam', 'got', 'thing', 'mind']
['thank', 'god', 'friday', 'jgh']
['love']
['timetunnel', 'quit', 'sure', 'radio', 'set', 'heart']
['hiii', 'jack', 'ili']
['play', 'domino', 'pub', 'got', 'quit', 'heat', 'enjoy', 'though']
['prob']
['enjoy', 'sorri', 'hastili', 'type', 'messag']
['thank']
['say', 'big', 'thank', 'person', 'came', 'idea', 'screenshot']
['true', 'pakistani']
['mention']
['bam', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'love']
['point', 'dreamteam', 'gooo', 'bailey', 'pbbgold']
['thank']
['drank']
['old', 'pic']
['follow', 'amp', 'follow', 'back']
['havent', 'gotten', 'sleep', 'hour']
['welsh', 'wale', 'today', 'yippe']
['done']
['happi', 'birthday', 'babi', 'miss', 'much', 'love', 'much']
['thank', 'bro']
['that', 'lord']
['sweet']
['like', 'michael', 'thank', 'kind', 'word', 'cheer']
['morn', 'realli', 'ure', 'alreadi', 'fun', 'caus', 'weekend', 'right', 'ure', 'futur', 'amaz', 'night']
['wait', 'peopl', 'call', 'bigot']
['usual', 'front', 'back', 'squat']
['much', 'fun', 'realli', 'enjoy', 'hope', 'next', 'contest', 'come', 'soon']
['dobar', 'dan', 'brand', 'new', 'heavi', 'musicolog', 'day']
['look', 'like', 'great', 'way', 'spend', 'friday', 'afternoon', 'enjoy', 'marathon', 'iflix']
['need', 'someon', 'talk', 'alway', 'keep', 'head']
['offici', 'graduat']
['glad', 'cri']
['thank']
['yep', 'expert', 'bisexu', 'good', 'luck']
['minal', 'aidzin']
['follow', 'amp', 'follow', 'back']
['plan', 'read', 'brand', 'new', 'cook', 'book', 'figur', 'make', 'dinner', 'tonight']
['lol', 'tough', 'choic', 'tbh', 'realli', 'like', 'everi', 'song', 'other']
['welcom']

In [17]:
print(positive_tweets_1[110])

['alreadi', 'afternoon', 'let', 'read', 'kahfi', 'day', 'finish']

In [18]:
pd.DataFrame(positive_tweets_1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4953 non-null   object
 1   1       4397 non-null   object
 2   2       3693 non-null   object
 3   3       3091 non-null   object
 4   4       2475 non-null   object
 5   5       2011 non-null   object
 6   6       1640 non-null   object
 7   7       1228 non-null   object
 8   8       925 non-null    object
 9   9       641 non-null    object
 10  10      409 non-null    object
 11  11      226 non-null    object
 12  12      118 non-null    object
 13  13      49 non-null     object
 14  14      25 non-null     object
 15  15      11 non-null     object
 16  16      5 non-null      object
 17  17      4 non-null      object
 18  18      2 non-null      object
 19  19      1 non-null      object
dtypes: object(20)
memory usage: 781.4+ KB

In [19]:
pd.DataFrame(negative_tweets_1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4934 non-null   object
 1   1       4344 non-null   object
 2   2       3596 non-null   object
 3   3       2855 non-null   object
 4   4       2235 non-null   object
 5   5       1814 non-null   object
 6   6       1443 non-null   object
 7   7       1162 non-null   object
 8   8       905 non-null    object
 9   9       656 non-null    object
 10  10      423 non-null    object
 11  11      268 non-null    object
 12  12      148 non-null    object
 13  13      75 non-null     object
 14  14      31 non-null     object
 15  15      17 non-null     object
 16  16      7 non-null      object
 17  17      4 non-null      object
 18  18      3 non-null      object
 19  19      2 non-null      object
dtypes: object(20)
memory usage: 781.4+ KB

#creat lable and list

In [20]:
#creat list with one coul and 5000 row equal the number of rows of the lsit
positive_lable=[1]*len(positive_tweets_1)
negative_lable=[0]*len(negative_tweets_1)

In [21]:
# we have now +ve tweets and -Ve tweets and we have 0 +ver lable and 1 as -Ve lael
# we need to contacte them
tweets=positive_tweets_1+negative_tweets_1
lables=positive_lable+negative_lable

In [ ]:
#Get vocabulary (unique words)

In [22]:
#lables

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 ...]

In [23]:
#creat table (data fram ) by your self define the coulmn and value to be added
pd.DataFrame({'Scrabed_Tweets':tweets,"O/P_Lable":lables})
#i wanna display 1st 10 rows
pd.DataFrame({'Scrabed_Tweets':tweets,"O/P_Lable":lables}).head(10)

                                      Scrabed_Tweets  O/P_Lable
0   [followfriday, top, engag, member, commun, week]          1
1  [hey, jame, odd, plea, call, contact, centr, a...          1
2  [listen, last, night, bleed, amaz, track, scot...          1
3                                          [congrat]          1
4  [yeaaaah, yippppi, accnt, verifi, rqst, succee...          1
5             [one, irresist, flipkartfashionfriday]          1
6  [dont, like, keep, love, custom, wait, long, h...          1
7  [second, thought, there, enough, time, new, sh...          1
8                                  [jgh, bayan, bye]          1
9  [act, mischiev, call, etl, layer, inhous, ware...          1

In [24]:
pd.DataFrame({'Scrabed_Tweets':tweets,"O/P_Lable":lables}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Scrabed_Tweets  10000 non-null  object
 1   O/P_Lable       10000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 156.4+ KB

In [25]:
zip_data = list(zip(tweets, lables))
random.shuffle(zip_data)
tweets, lables = zip(*zip_data)

In [26]:
pd.DataFrame({'Scrabed_Tweets':tweets,"O/P_Lable":lables}).head(10)

                                      Scrabed_Tweets  O/P_Lable
0  [cours, that, understand, notic, issu, well, p...          1
1                        [follow, amp, follow, back]          1
2  [kik, senight, kik, kikmeboy, gay, teen, amate...          0
3                            [hehe, smile, ear, ear]          1
4                                 [haha, know, mess]          1
5                                 [mano, hold, hand]          1
6                                                 []          1
7                                            [thank]          1
8                     [glad, sonal, instagram, what]          1
9                [love, store, best, chocol, select]          1

# Word Embeding
1- Layer Embedidng in DL
2- word2Vec
3- Glove
4- Fasttext

In [36]:
#Embedding
#apply test representaiton by embeding

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [29]:
#flatten  Flatten into one list of words
all_words=[]
for tweet in tweets:
  for word in tweet:
    all_words.append(word)

In [30]:
#Get vocabulary (unique words)

voc = set (all_words)
voc_size = len(voc)

In [31]:
voc_size

9553

In [43]:

tweets = list(tweets)
labels = list(lables)
# join tokens back into sentence
Onehot_prep = [one_hot (" ".join(tweet), voc_size ) for tweet in tweets]
#the for tweet in tweets coz That’s because keras.preprocessing.text.one_hot()
#works on one string at a time, not on a list of strings.

#Your tweets list doesn’t contain strings, it contains
# lists of tokens (because you already preprocessed them earlier).

In [44]:
print(Onehot_prep[:5])

[[6493, 7872, 83603, 33299, 40695, 63096, 4843, 19170, 77502, 16416], [87165, 47374, 87165, 69396], [41860, 68001, 41860, 74516, 65103, 96544, 85250, 34492, 80452], [33012, 94981, 55517, 55517], [44155, 39289, 88472]]

In [47]:
#apply padding
sent_lenght = 8
embeded_tweets= pad_sequences(Onehot_prep,padding='pre',maxlen=sent_lenght)
#define
#sent length = 8 words
#word vectore repsetnation = 10 for example
#voc_size number of unqe words we have in or our sets

In [48]:
#Apply Model for EMbded
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_lenght))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [49]:
#predect Data
model.predict(embeded_tweets[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step

array([[ 0.01654765,  0.00160365,  0.03312453,  0.00421169, -0.0009368 ,
         0.02978808, -0.02216253,  0.01327908,  0.04118707,  0.04224483],
       [ 0.00202424,  0.02492621,  0.03635404,  0.04728113,  0.03066598,
         0.02360684,  0.01321826,  0.04675952, -0.0377076 , -0.04331464],
       [-0.03121262,  0.0494622 , -0.02326591,  0.00216863, -0.00988318,
         0.03833586, -0.00462496, -0.00388495,  0.01087673,  0.01475007],
       [ 0.00789427, -0.04348931,  0.00677359,  0.01694337, -0.04157122,
        -0.02871999, -0.00563763, -0.0136417 , -0.002372  , -0.00949639],
       [ 0.02464327,  0.00578577,  0.01725307,  0.01396297, -0.01232159,
        -0.01966715,  0.02420131, -0.01176448,  0.01616028,  0.0440647 ],
       [ 0.02449906, -0.03368508,  0.02541837, -0.01410953,  0.03787932,
        -0.00130128,  0.00453969, -0.01735293, -0.03120352,  0.01992849],
       [ 0.03282446,  0.02600432,  0.03455538, -0.02219766,  0.01211538,
        -0.03542561, -0.03256956,  0.01225996, -0.01319817, -0.04350584],
       [-0.03392505,  0.03621645, -0.0180379 ,  0.04656586, -0.03863866,
         0.02150637, -0.03025919, -0.04607666, -0.01324575,  0.00241115]],
      dtype=float32)